### ISSUE TITLE
MySql and Phpmyadmin setup

### ISSUE THREAD

**Issue by paladhamma** [palasangha/Treasures-Of-Dhamma#6]
How to view mysql in terminal and setup phpmyadmin for the same?

**Comment by paladhamma** [comment]
1. For MySQL run `docker exec -ti esmero-db bash`
On entering the docker container esmero-db opens. 
There type - `mysql -u root -p` enter the password.

type: `create user 'dhamma'@'%' identified by 'dhamma';` -> This creates new use dhamma.
`grant all privileges on *.* to 'dhamma'@'%' with grant option;` -> All privileges are granted to this user.
To view databases type `show databases;`

2. For PHPMyAdmin follow below 3 links:
a. https://www.youtube.com/watch?v=DjljekW50Qg
b. https://github.com/awstechguide/scripts/blob/master/docker/install-mysql-and-phpmyadmin-on-docker.md
c. https://towardsdatascience.com/how-to-run-mysql-and-phpmyadmin-using-docker-17dfe107eab7

Follow the youtube video - start after the MySQL-container part. 

Steps:
a. `sudo apt-get update && sudo apt-get upgrade -y`
b. `sudo apt-get install openjdk-11-jre -y`
c. `sudo apt-get update`
d. `docker pull phpmyadmin/phpmyadmin:latest` -> To pull phpmyadmin image locally
e.  Edit docker-compose.yml file and add the following code: 

```
phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
     # PMA_USER: root
     # PMA_PASSWORD: root
    networks:
      - host-net
      - esmero-net
    ports:
      - "8899:80"
```
f. `docker-compose up -d` -> to update docker-compose and create new container PHPMyAdmin from the image pulled earlier.

**PHPMyAdmin is set in 8899 port so run <domain>:8899 in this case, log in with user id - dhamma and password created.**
